# Generated by Django 6.0.3 on 2026-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Изображение'),
        ),
    ]
