# Generated by Django 6.0.3 on 2026-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplaces/', verbose_name='Изображение'),
        ),
    ]
