# Generated by Django 6.0.3 on 2026-06-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplace_price_alter_marketplace_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
