# Generated by Django 6.1.1 on 2026-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Комментарий будет виден после одобрения', verbose_name='Одобрено модератором'),
        ),
    ]
